### ISSUE TITLE
Viz_video.py can not be run

### ISSUE THREAD

**Issue by KangchengLiu** [fregu856/ebms_3dod#4]
The `3dod/viz_video.py`, which is the code for creating the Youtube video with qualitative results can not be run successfully, please update it with corrections, thanks

**Comment by fregu856** [comment]
Hi,

You will have to uncomment the lines at the bottom of https://github.com/fregu856/ebms_3dod/blob/main/3dod/mmdet/models/detectors/single_stage.py to first save the predicted bboxes, and then modify line 529 of https://github.com/fregu856/ebms_3dod/blob/main/3dod/viz_video.py accordingly.

**Comment by insanebai** [comment]
@KangchengLiu 
Hello, I want to use this code now, but I encountered a configuration problem. How did you configure the environment for this code? Thank you.
